USE PhoneSt;
GO

-- Kiểm tra xem các cột đã tồn tại chưa và thêm nếu chưa có
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'GoogleId')
BEGIN
    ALTER TABLE Users ADD GoogleId NVARCHAR(50);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'VerifiedEmail')
BEGIN
    ALTER TABLE Users ADD VerifiedEmail BIT DEFAULT (0);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'GivenName')
BEGIN
    ALTER TABLE Users ADD GivenName NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'FamilyName')
BEGIN
    ALTER TABLE Users ADD FamilyName NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'GoogleLink')
BEGIN
    ALTER TABLE Users ADD GoogleLink NVARCHAR(255);
END

-- Thêm dữ liệu mẫu vào bảng Roles nếu chưa có
IF NOT EXISTS (SELECT * FROM Roles WHERE RoleName = 'Admin')
BEGIN
    INSERT INTO Roles (RoleName) VALUES ('Admin');
END

IF NOT EXISTS (SELECT * FROM Roles WHERE RoleName = 'Customer')
BEGIN
    INSERT INTO Roles (RoleName) VALUES ('Customer');
END

GO 